name: Build APK with EAS

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build APK with EAS
      run: |
        npx eas-cli build \
          --platform android \
          --profile preview \
          --non-interactive \
          --no-wait
          
    - name: Download APK artifact
      if: success()
      run: |
        npx eas-cli build:list --limit 1 --status finished
